services:
  - type: web
    name: flask-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
